-- CreateTable
CREATE TABLE "Player" (
    "id" SERIAL NOT NULL,
    "favorite" BOOLEAN DEFAULT false,
    "rookie" BOOLEAN DEFAULT false,
    "selected" BOOLEAN DEFAULT false,
    "taken" BOOLEAN DEFAULT false,
    "bucket" TEXT,
    "group" INTEGER,
    "firstName" TEXT,
    "lastName" TEXT,
    "staceyNotes" TEXT,
    "laurenNotes" TEXT,
    "bjNotes" TEXT,
    "notes" TEXT,
    "height" TEXT,
    "jerseySize" TEXT,
    "pronouns" TEXT,
    "womens" BOOLEAN,
    "offDefCaptainExperience" TEXT,
    "offDefCaptainInterest" TEXT,
    "socialCaptainInterest" BOOLEAN DEFAULT false,
    "ngffl" BOOLEAN DEFAULT false,
    "speed" INTEGER,
    "agility" INTEGER,
    "handEyeCoordination" INTEGER,
    "competitiveness" INTEGER,
    "footballExperience" INTEGER,
    "offensiveKnowledge" INTEGER,
    "defensiveKnowledge" INTEGER,
    "totalScore" INTEGER,
    "qb" TEXT,
    "blocker" TEXT,
    "wr" TEXT,
    "slot" TEXT,
    "rusher" TEXT,
    "safety" TEXT,
    "corner" TEXT,
    "linebacker" TEXT,
    "missingWeeks" BOOLEAN DEFAULT false,
    "whichWeeks" TEXT,
    "additionalContext" TEXT,
    "otherExperience" TEXT,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("id")
);
