-- CreateTable
CREATE TABLE "Player" (
    "id" SERIAL NOT NULL,
    "rookie" BOOLEAN,
    "selected" BOOLEAN,
    "taken" BOOLEAN,
    "bucket" TEXT,
    "group" INTEGER,
    "firstName" TEXT,
    "lastName" TEXT,
    "staceyNotes" TEXT,
    "laurenNotes" TEXT,
    "bjNotes" TEXT,
    "notes" TEXT,
    "height" TEXT,
    "jerseySize" TEXT,
    "pronouns" TEXT,
    "womens" BOOLEAN,
    "offDefCaptainExperience" TEXT,
    "offDefCaptainInterest" TEXT,
    "socialCaptainInterest" TEXT,
    "ngffl" BOOLEAN,
    "speed" INTEGER,
    "agility" INTEGER,
    "handEyeCoordination" INTEGER,
    "competitiveness" INTEGER,
    "footballExperience" INTEGER,
    "offensiveKnowledge" INTEGER,
    "defensiveKnowledge" INTEGER,
    "totalScore" INTEGER,
    "qb" TEXT,
    "blocker" TEXT,
    "wr" TEXT,
    "slot" TEXT,
    "rusher" TEXT,
    "safety" TEXT,
    "corner" TEXT,
    "linebacker" TEXT,
    "missingWeeks" BOOLEAN,
    "whichWeeks" TEXT,
    "additionalContext" TEXT,
    "otherExperience" TEXT,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("id")
);
