-- Drop old unified table
DROP TABLE "Player";

-- Create QB table
CREATE TABLE "Qb" (
    "id" SERIAL NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "drafted" BOOLEAN NOT NULL DEFAULT false,
    "selected" BOOLEAN NOT NULL DEFAULT false,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "height" TEXT,
    "pronouns" TEXT,
    "womens" BOOLEAN NOT NULL DEFAULT false,
    "totalScore" INTEGER,
    "speed" INTEGER,
    "agility" INTEGER,
    "handEyeCoordination" INTEGER,
    "competitiveness" INTEGER,
    "footballExperience" INTEGER,
    "offensiveKnowledge" INTEGER,
    "defensiveKnowledge" INTEGER,
    "qb" TEXT,
    "blocker" TEXT,
    "wr" TEXT,
    "slot" TEXT,
    "rusher" TEXT,
    "safety" TEXT,
    "corner" TEXT,
    "linebacker" TEXT,
    "missingWeeks" BOOLEAN NOT NULL DEFAULT false,
    "whichWeeks" TEXT,
    "additionalContext" TEXT,
    "otherExperience" TEXT,
    "offDefCaptainExperience" TEXT,
    "offDefCaptainInterest" TEXT,
    "socialCaptainInterest" BOOLEAN NOT NULL DEFAULT false,
    "returningMember" BOOLEAN NOT NULL DEFAULT false,
    "ngffl" BOOLEAN NOT NULL DEFAULT false,
    "summitMhcInterest" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Qb_pkey" PRIMARY KEY ("id")
);

-- Create ReturningPlayer table
CREATE TABLE "ReturningPlayer" (
    "id" SERIAL NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "favorite" BOOLEAN NOT NULL DEFAULT false,
    "selected" BOOLEAN NOT NULL DEFAULT false,
    "drafted" BOOLEAN NOT NULL DEFAULT false,
    "rejected" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "bucket" TEXT,
    "group" INTEGER,
    "height" TEXT,
    "jerseySize" TEXT,
    "pronouns" TEXT,
    "womens" BOOLEAN NOT NULL DEFAULT false,
    "offDefCaptainExperience" TEXT,
    "offDefCaptainInterest" TEXT,
    "socialCaptainInterest" BOOLEAN NOT NULL DEFAULT false,
    "ngffl" BOOLEAN NOT NULL DEFAULT false,
    "speed" INTEGER,
    "agility" INTEGER,
    "handEyeCoordination" INTEGER,
    "competitiveness" INTEGER,
    "footballExperience" INTEGER,
    "offensiveKnowledge" INTEGER,
    "defensiveKnowledge" INTEGER,
    "totalScore" INTEGER,
    "qb" TEXT,
    "blocker" TEXT,
    "wr" TEXT,
    "slot" TEXT,
    "rusher" TEXT,
    "safety" TEXT,
    "corner" TEXT,
    "linebacker" TEXT,
    "missingWeeks" BOOLEAN NOT NULL DEFAULT false,
    "whichWeeks" TEXT,
    "additionalContext" TEXT,
    "otherExperience" TEXT,

    CONSTRAINT "ReturningPlayer_pkey" PRIMARY KEY ("id")
);

-- Create Rookie table
CREATE TABLE "Rookie" (
    "id" SERIAL NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "favorite" BOOLEAN NOT NULL DEFAULT false,
    "selected" BOOLEAN NOT NULL DEFAULT false,
    "drafted" BOOLEAN NOT NULL DEFAULT false,
    "rejected" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "bucket" TEXT,
    "group" INTEGER,
    "height" TEXT,
    "jerseySize" TEXT,
    "pronouns" TEXT,
    "womens" BOOLEAN NOT NULL DEFAULT false,
    "offDefCaptainExperience" TEXT,
    "offDefCaptainInterest" TEXT,
    "socialCaptainInterest" BOOLEAN NOT NULL DEFAULT false,
    "ngffl" BOOLEAN NOT NULL DEFAULT false,
    "speed" INTEGER,
    "agility" INTEGER,
    "handEyeCoordination" INTEGER,
    "competitiveness" INTEGER,
    "footballExperience" INTEGER,
    "offensiveKnowledge" INTEGER,
    "defensiveKnowledge" INTEGER,
    "totalScore" INTEGER,
    "qb" TEXT,
    "blocker" TEXT,
    "wr" TEXT,
    "slot" TEXT,
    "rusher" TEXT,
    "safety" TEXT,
    "corner" TEXT,
    "linebacker" TEXT,
    "missingWeeks" BOOLEAN NOT NULL DEFAULT false,
    "whichWeeks" TEXT,
    "additionalContext" TEXT,
    "otherExperience" TEXT,

    CONSTRAINT "Rookie_pkey" PRIMARY KEY ("id")
);

-- Uniqueness for name-based matching across uploads
CREATE UNIQUE INDEX "Qb_firstName_lastName_key" ON "Qb"("firstName", "lastName");
CREATE UNIQUE INDEX "ReturningPlayer_firstName_lastName_key" ON "ReturningPlayer"("firstName", "lastName");
CREATE UNIQUE INDEX "Rookie_firstName_lastName_key" ON "Rookie"("firstName", "lastName");
